### PR TITLE
Fix `maxAge` start on Promise settlement

### LINKED ISSUE #22: `maxAge` starts on function call instead of on fulfillment
Copy of https://github.com/sindresorhus/mem/issues/81 since here it's more appropriet as @fregante suggested.

I've noticed, that when memoizing long lasting async functions, the maxAge is evaluated relative to the moment when function call started. But in case of sync functions it is evaluated relative to the moment the function was resolved.

Expected: Sync functions as is. Async functions (functions that return promise) maxAge should be evaluated relative to when promise is resolved.

Current: Async functions maxAge is evaluated relative to the moment when Promise is returned. (Not resolved, as I would expect!)

Fix: Dirty fix is add await, but then all memoized function will be async. Clean fix is to change beaviour base on function return type. If Promise then wait till it's resolved. Else as is now.

I really appriciate your work, it's great library, just I can't use it because of this unexpected behaviour. Or if I miss understood something and it's working correctly I'm in advance sorry.

### PR DESCRIPTION
**Pull request by krystofwoldrich**
This is PR base on issue https://github.com/sindresorhus/p-memoize/issues/22.

I've tried to keep the dependency on mem at firt, but I've not found any solution where it would make sense. After I added the maxAge map here to the `p-memoize` there wasn't basically any reason to keep mem in here. Maybe just for the `clear` function but in my opinien it is cleaner to have here `cacheStore` then to have dependency just for that purpose.

The only change is in the maxAge, all other behaviour should be unchanged.
Alltho the code would be cleaner if we would create from every function -> async function but I would rather have a bit more complicated code and keep the behaviour.

Let me know what you think or if you see any other nice, cleaner solutions.

---

Fixes #22

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -1,43 +1,74 @@
...
+	const {maxAge, cacheKey} = options;
 	const cache = options.cache || new Map();
-	const cacheKey = options.cacheKey || (([firstArgument]) => firstArgument);
 
-	const memoized = mem(fn, {
-		...options,
-		cache,
-		cacheKey
-	});
+	if (!isNaN(maxAge)) {
```
Comment (sindresorhus) [inline index.js:11]: It should fail loudly with a `TypeError` if `maxAge` doesn't pass `Number.isSafeInteger`.

File: index.js [hunk 2]
```diff
@@ -1,43 +1,74 @@
...
+				data: result,
+				maxAge: maxAge ? Date.now() + maxAge : Number.POSITIVE_INFINITY
 			});
+
+			if (!cachePromiseRejection && resultError) {
+				cache.delete(key);
+			}
+		};
+
+		if (result && result instanceof Promise) {
```
Comment (sindresorhus) [inline index.js:37]: `instanceof` is not a good way to check for promises.

```suggestion
		if (result && typeof result.then === 'function') {
```

File: index.js [hunk 3]
```diff
@@ -1,43 +1,74 @@
...
+		if (cacheItem) {
+			return cacheItem.data;
+		}
 
-		if (!cachePromiseRejection && cacheItem && cacheItem.catch) {
-			cacheItem.catch(() => {
-				cache.delete(cacheKey(arguments_));
+		const result = fn.apply(this, arguments_);
+
+		let resultError = null;
```
Comment (sindresorhus) [inline index.js:25]:
```suggestion
		let resultError;
```

File: index.js (hunk 2 above)
Comment (sindresorhus) [reply index.js:37]: Why are you checking for a promise at all? You can just use `Promise.resolve()`.

**Review by sindresorhus — CHANGES_REQUESTED** [review]

File: index.js (hunk 2 above)
Comment (krystofwoldrich) [reply index.js:37]: Because `Promise.resolve()` returns a promise and I think it is better to keep the function working as it is now. That means when it gets a non-promise returning function it won't change it to a promise returrning function.

File: index.js (hunk 1 above)
Comment (krystofwoldrich) [reply index.js:11]: OK. Thanks, this if condition didn't make sense.

File: index.js (hunk 2 above)
Comment (sindresorhus) [reply index.js:37]: The docs are pretty clear about it only accepting promise-returning functions though, even though we didn't actually validate that:

> Promise-returning or async function to be memoized.

Comment (krystofwoldrich) [reply index.js:37]: Yes, you're right. I guess it's a matter of taste, I didn't want to change the behaviour if not necessary.

But if you look at it as a "bug", then it would make sense to change now.

Comment (sindresorhus) [reply index.js:37]: Yeah, I see it as a bug.

Comment (krystofwoldrich) [reply index.js]: I've used the  `Promise.resolve()` now.

**Comment by krystofwoldrich** [comment]
@sindresorhus You can take a second look, I've made the changes you mentioned.

File: index.js [hunk 4]
```diff
@@ -1,43 +1,65 @@
...
+		if (cacheItem) {
+			return cacheItem.data;
 		}
 
-		return cacheItem;
+		const result = fn.apply(this, arguments_);
+
+		let resultError;
+		try {
+			return await Promise.resolve(result);
```
Comment (fregante) [inline index.js:29]: Why wrap this into a promise.resolve?

File: index.js [hunk 5]
```diff
@@ -1,43 +1,65 @@
...
+		} catch (error) {
+			resultError = error;
```
Comment (fregante) [inline index.js:31]: Why not just clear the cache here?

File: index.js [hunk 6]
```diff
@@ -1,43 +1,65 @@
...
+			throw error;
+		} finally {
+			cache.set(key, {
```
Comment (fregante) [inline index.js:34]: This means the cache is set AFTER the promise is fulfilled, which means these 2 calls will not be memoized:

```js 
void memFetch()
void memFetch()
```

File: index.js [hunk 7]
```diff
@@ -1,43 +1,65 @@
...
+				data: result,
+				maxAge: maxAge ? Date.now() + maxAge : Number.POSITIVE_INFINITY
+			});
+
+			if (!cachePromiseRejection && resultError) {
```
Comment (fregante) [inline index.js:39]: This position means that the cache is being set and then immediately deleted 🤷‍♂️

**Review by fregante — COMMENTED** [review]
A bit late to the party, but I see a major issue and a couple of improvements

File: index.js (hunk 6 above)
Comment (fregante) [reply index.js:34]: To achieve both initial call memoization *and* move the start time to the fulfillment, it'd have to first store the call without expiration _and then_ re-add it with the right expiration once it fulfills.

File: index.js (hunk 4 above)
Comment (krystofwoldrich) [reply index.js:29]: True, that will make it cleaner.

File: index.js (hunk 5 above)
Comment (krystofwoldrich) [reply index.js:31]: I think this is only a matter of preference.
I see this as a more clear approach to have only one cache set.

File: index.js (hunk 6 above)
Comment (krystofwoldrich) [reply index.js:34]: I think if someone wants this behaviour there is mem that does exactly that.

File: index.js (hunk 7 above)
Comment (krystofwoldrich) [reply index.js:39]: True, this if could be written differently, so cache is set only when it should be.

File: index.js (hunk 6 above)
Comment (sindresorhus) [reply index.js:34]: It's totally valid to start multiple promises at the same time though. I agree with @fregante that this is a regression.

Comment (sindresorhus) [reply index.js:34]: > Since it should be oriented on promise function and this is more not promise usecase.

I don't think @fregante made it clear enough in that example, but those are async functions.

Comment (krystofwoldrich) [reply index.js:34]: OK, guys, I've created a new PR (https://github.com/sindresorhus/p-memoize/pull/25) which solves this.

File: index.js (hunk 7 above)
Comment (krystofwoldrich) [reply index.js:39]: Also, this is solved here https://github.com/sindresorhus/p-memoize/pull/25

File: index.js (hunk 4 above)
Comment (krystofwoldrich) [reply index.js:29]: I removed the resolve here https://github.com/sindresorhus/p-memoize/pull/25
